[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "uvicorn api_main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Environment variables will be set in Railway dashboard
# Required: REPLICATE_API_TOKEN, GOOGLE_API_KEY, GOOGLE_SEARCH_ENGINE_ID